name: Setup CommandBox
description: Sets up CommandBox for GitHub Actions
runs:
  using: "composite"
  steps: 
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.0
      with:
        java-version: 11 
    - name: Install CommandBox
      run: |
        curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
        sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
        sudo apt-get update && sudo apt-get --assume-yes install rsync jq commandbox
        box install commandbox-cfconfig,commandbox-dotenv,commandbox-docbox
        box config set endpoints.forgebox.APIToken=${{ secrets.FORGEBOX_API_KEY }} > /dev/null
