name: Setup CommandBox
description: Sets up CommandBox for GitHub Actions

branding:
  icon: terminal
  color: blue

inputs:
  forgeboxAPIKey:
    description: ForgeBox API Key
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -SL -o box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
        unzip box.zip -d /usr/local/bin
        box install commandbox-cfconfig,commandbox-dotenv
        if [[ ! -z "${{ inputs.forgeboxAPIKey }}" ]] ; then
          box config set endpoints.forgebox.APIToken=${{ inputs.forgeboxAPIKey }} > /dev/null
        fi
