name: Setup CommandBox
description: Sets up CommandBox for GitHub Actions

branding:
  icon: terminal
  color: blue

inputs:
  forgeboxAPIKey:
    description: "ForgeBox API Key"
    required: false
    default: 'none'
  version:
    description: "CommandBox version to install"
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Latest Stable or Specific Version
        if [[ "${{ inputs.version }}" == "latest" ]] ; then
          echo "Installing Latest Stable CommandBox"
          curl -SL -o box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
        else
          echo "Installing CommandBox v${{ inputs.version }}"
          curl -SL -o box.zip https://downloads.ortussolutions.com/ortussolutions/commandbox/${{ inputs.version }}/commandbox-bin-${{ inputs.version }}.zip
        fi
        # Debug download
        #ls -l
        # Unzip and Install
        unzip box.zip -d /usr/local/bin/
        # Install global dependencies
        box install commandbox-cfconfig,commandbox-dotenv
        # Add ForgeBox Key
        if [[ "${{ inputs.forgeboxAPIKey }}" != "none" ]] ; then
          echo "Setting up ForgeBox API Key..."
          box config set endpoints.forgebox.APIToken=${{ inputs.forgeboxAPIKey }} > /dev/null
        fi
