on: [push, pull_request]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Ensures the action is working
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run local action
      uses: ./
